
export type Term = {
  id: string;
  term: string;
  slug: string;
  definition: string;
  example: string;
};

export const terms: Term[] = [
  {
    id: 'a-b-testing',
    term: 'A/B Testing',
    slug: 'a-b-testing',
    definition: 'A controlled experiment comparing two versions of a system or UI (A and B) to determine which performs better based on real user behavior.',
    example: 'An e-commerce site runs an A/B test by showing 50% of users a green "Buy Now" button and the other 50% a blue one to see which color leads to more sales.',
  },
  {
    id: 'aar-android-archive',
    term: 'AAR (Android Archive)',
    slug: 'aar-android-archive',
    definition: 'A package file that contains compiled Android libraries, resources, and manifests, used for distributing reusable Android components.',
    example: 'Instead of copying code, a developer includes a third-party image loading library in their project by adding its AAR file as a dependency.',
  },
  {
    id: 'abi-application-binary-interface',
    term: 'ABI (Application Binary Interface)',
    slug: 'abi-application-binary-interface',
    definition: 'Defines how software components interact at the binary level—calling conventions, data types, register usage, etc. Critical for cross-platform compatibility.',
    example: 'For an Android app with C++ code to run on both ARM and x86 processors, the developer must build separate native libraries for each target ABI.',
  },
  {
    id: 'abr-adaptive-bitrate-streaming',
    term: 'ABR (Adaptive Bitrate Streaming)',
    slug: 'abr-adaptive-bitrate-streaming',
    definition: 'A streaming method where video/audio quality automatically adjusts to the user’s internet speed to prevent buffering.',
    example: 'When you watch Netflix, the video quality might start low and then become sharp and clear. That\'s ABR adjusting the stream to your network connection.',
  },
  {
    id: 'acid-properties',
    term: 'ACID Properties',
    slug: 'acid-properties',
    definition: 'A set of rules ensuring reliable database transactions: Atomicity, Consistency, Isolation, Durability.',
    example: 'When you transfer money, the bank\'s database uses ACID properties to ensure the money is successfully withdrawn from one account and deposited into another as a single, indivisible operation.',
  },
  {
    id: 'ack-acknowledgment-packet',
    term: 'ACK (Acknowledgment Packet)',
    slug: 'ack-acknowledgment-packet',
    definition: 'A signal sent in networking indicating that data was successfully received.',
    example: 'When you send a file, your computer waits for an ACK from the server for each piece of data. If it doesn\'t get one, it re-sends that piece.',
  },
  {
    id: 'acl-access-control-list',
    term: 'ACL (Access Control List)',
    slug: 'acl-access-control-list',
    definition: 'A permission list specifying which users or systems can access certain files, directories, or services.',
    example: 'A network administrator configures a router\'s ACL to block all traffic from a specific IP address to enhance security.',
  },
  {
    id: 'acpi-advanced-configuration-and-power-interface',
    term: 'ACPI (Advanced Configuration and Power Interface)',
    slug: 'acpi-advanced-configuration-and-power-interface',
    definition: 'A standard that allows the OS to control hardware power states—sleep, hibernate, CPU throttling, etc.',
    example: 'When you close your laptop lid and it goes to sleep, the ACPI standard is what allows the operating system to manage that power-saving state.',
  },
  {
    id: 'active-directory-ad',
    term: 'Active Directory (AD)',
    slug: 'active-directory-ad',
    definition: 'Microsoft’s centralized directory service used for managing users, computers, credentials, and policies in enterprise networks.',
    example: 'In a large company, IT uses Active Directory to create a new employee\'s account, giving them access to the corporate network, email, and shared files with a single login.',
  },
  {
    id: 'ad-hoc-network',
    term: 'Ad Hoc Network',
    slug: 'ad-hoc-network',
    definition: 'A temporary wireless network created without routers or infrastructure, often peer-to-peer.',
    example: 'During a power outage, students created an ad hoc network with their laptops to share files directly without needing a Wi-Fi router.',
  },
  {
    id: 'address-bus',
    term: 'Address Bus',
    slug: 'address-bus',
    definition: 'A communication system in a CPU that transfers memory addresses, determining which memory location to access.',
    example: 'When your computer needs to read data, the CPU sends the memory address of that data over the address bus to the RAM.',
  },
  {
    id: 'address-space-layout-randomization-aslr',
    term: 'Address Space Layout Randomization (ASLR)',
    slug: 'address-space-layout-randomization-aslr',
    definition: 'A security technique that randomizes memory address locations to defend against buffer overflows.',
    example: 'Modern operating systems use ASLR to make it harder for malware to predict where to inject malicious code into a running application.',
  },
  {
    id: 'aes-advanced-encryption-standard',
    term: 'AES (Advanced Encryption Standard)',
    slug: 'aes-advanced-encryption-standard',
    definition: 'A widely used symmetric encryption algorithm with 128-, 192-, or 256-bit keys, used in secure communications.',
    example: 'The Wi-Fi Protected Access (WPA2/3) standard uses AES to encrypt the data transmitted between your device and the router.',
  },
  {
    id: 'aft-android-file-transfer',
    term: 'AFT (Android File Transfer)',
    slug: 'aft-android-file-transfer',
    definition: 'A protocol and tool for transferring files between Android devices and computers.',
    example: 'To move photos from his Android phone to his MacBook, he used the Android File Transfer application.',
  },
  {
    id: 'agile',
    term: 'Agile',
    slug: 'agile',
    definition: 'A project management methodology that uses an incremental, iterative approach. Instead of a big-bang launch, teams deliver work in small, but consumable, increments. The goal is to provide value to customers faster and with fewer headaches.',
    example: 'A software team uses the Agile method, working in two-week "sprints" to release new features incrementally, gathering feedback after each release to guide the next phase of development.',
  },
  {
    id: 'aidl-android-interface-definition-language',
    term: 'AIDL (Android Interface Definition Language)',
    slug: 'aidl-android-interface-definition-language',
    definition: 'A framework in Android for defining communication interfaces between processes.',
    example: 'A music player app uses AIDL to allow other apps to control playback (play, pause, skip) even when they are running in separate processes.',
  },
  {
    id: 'ai-model-quantization',
    term: 'AI Model Quantization',
    slug: 'ai-model-quantization',
    definition: 'Reducing precision (e.g., from float32 to int8) to make AI models smaller and faster with minimal accuracy loss.',
    example: 'To run an image recognition model on a smartphone, developers use quantization to shrink the model size, making it faster and more battery-efficient.',
  },
  {
    id: 'aio-all-in-one-computer',
    term: 'AIO (All-in-One Computer)',
    slug: 'aio-all-in-one-computer',
    definition: 'A computer where the display and internal hardware are combined into one chassis.',
    example: 'The Apple iMac is a well-known example of an AIO computer, with all its components housed behind the screen.',
  },
  {
    id: 'aiops-artificial-intelligence-for-it-operations',
    term: 'AIOps (Artificial Intelligence for IT Operations)',
    slug: 'aiops-artificial-intelligence-for-it-operations',
    definition: 'The application of machine learning to automate IT monitoring, alerting, and incident response.',
    example: 'An AIOps platform analyzed thousands of server logs, detected an unusual pattern, and automatically alerted the IT team to a potential failure before it happened.',
  },
  {
    id: 'airgap-network',
    term: 'Airgap Network',
    slug: 'airgap-network',
    definition: 'A network completely isolated with no internet or external connectivity, used for maximum security.',
    example: 'Critical infrastructure systems, like those at a nuclear power plant, are kept on an airgap network to protect them from external cyberattacks.',
  },
  {
    id: 'ajax',
    term: 'AJAX',
    slug: 'ajax',
    definition: 'Asynchronous JavaScript and XML. A technique for creating fast and dynamic web pages. It allows web pages to be updated asynchronously by exchanging small amounts of data with the server behind the scenes.',
    example: 'When you like a post on social media and the like count updates without reloading the page, that is likely using AJAX.',
  },
  {
    id: 'alarm-manager-android',
    term: 'Alarm Manager (Android)',
    slug: 'alarm-manager-android',
    definition: 'A system service for scheduling time-based operations even when the app is not running.',
    example: 'A calendar app uses the Alarm Manager to schedule a notification that will fire at the exact time of a user\'s appointment.',
  },
  {
    id: 'algorithmic-complexity',
    term: 'Algorithmic Complexity',
    slug: 'algorithmic-complexity',
    definition: 'A formal measure (Big-O notation) describing how the time or space requirement of an algorithm scales.',
    example: 'An algorithm with O(n²) complexity will become significantly slower as the input size (n) grows compared to one with O(n) complexity.',
  },
  {
    id: 'alias-record-dns',
    term: 'Alias Record (DNS)',
    slug: 'alias-record-dns',
    definition: 'A DNS entry that points one domain to another, often using CNAME.',
    example: 'The administrator created a CNAME alias record so that "www.example.com" points to "example.com".',
  },
  {
    id: 'allocator-memory-allocator',
    term: 'Allocator (Memory Allocator)',
    slug: 'allocator-memory-allocator',
    definition: 'The low-level system that handles allocating and freeing memory blocks in programs.',
    example: 'In C++, the `new` keyword calls the memory allocator to find and reserve a block of memory for a new object.',
  },
  {
    id: 'amp-accelerated-mobile-pages',
    term: 'AMP (Accelerated Mobile Pages)',
    slug: 'amp-accelerated-mobile-pages',
    definition: 'A lightweight web framework designed to load extremely fast on mobile devices.',
    example: 'News articles that use AMP often appear with a lightning bolt icon in search results and load almost instantly when clicked.',
  },
  {
    id: 'amqp-advanced-message-queuing-protocol',
    term: 'AMQP (Advanced Message Queuing Protocol)',
    slug: 'amqp-advanced-message-queuing-protocol',
    definition: 'A binary protocol enabling reliable message delivery between distributed applications.',
    example: 'Financial systems use AMQP for guaranteed message delivery between different trading and processing services.',
  },
  {
    id: 'ansible',
    term: 'Ansible',
    slug: 'ansible',
    definition: 'An automation tool for configuration management, provisioning, and application deployment using YAML.',
    example: 'A DevOps engineer wrote an Ansible playbook to automatically configure and deploy a web server on 100 different machines.',
  },
  {
    id: 'android-runtime-art',
    term: 'Android Runtime (ART)',
    slug: 'android-runtime-art',
    definition: 'The modern Android application execution environment replacing Dalvik, using ahead-of-time compilation.',
    example: 'Thanks to ART, apps on modern Android devices often launch faster and run more efficiently because they are compiled to native code upon installation.',
  },
  {
    id: 'anomaly-detection',
    term: 'Anomaly Detection',
    slug: 'anomaly-detection',
    definition: 'The AI/ML process of detecting unusual patterns indicating errors, attacks, or system failures.',
    example: 'A credit card company uses anomaly detection to flag a transaction as potentially fraudulent if it occurs in a different country from the user\'s usual location.',
  },
  {
    id: 'antimalware-engine',
    term: 'Antimalware Engine',
    slug: 'antimalware-engine',
    definition: 'A system component that analyzes files/processes to detect viruses and malicious behavior.',
    example: 'Windows Defender\'s antimalware engine scanned the downloaded file and quarantined it after identifying it as a known trojan.',
  },
  {
    id: 'aot-compilation-ahead-of-time',
    term: 'AOT Compilation (Ahead-of-Time)',
    slug: 'aot-compilation-ahead-of-time',
    definition: 'Compiling code to machine language before execution, improving performance and startup time.',
    example: 'The .NET Core runtime uses AOT compilation to convert an application into a self-contained, high-performance executable.',
  },
  {
    id: 'api-gateway',
    term: 'API Gateway',
    slug: 'api-gateway',
    definition: 'A middleware layer that routes API requests, handles rate limiting, authentication, caching, etc.',
    example: 'Netflix uses an API Gateway to handle all incoming requests from its various apps, routing them to the correct microservice.',
  },
  {
    id: 'api-rate-limiting',
    term: 'API Rate Limiting',
    slug: 'api-rate-limiting',
    definition: 'Restricting how often clients can hit an API to prevent abuse or server overload.',
    example: 'The Twitter API has a rate limit that allows a developer to make only a certain number of requests every 15 minutes.',
  },
  {
    id: 'apk-android-package-kit',
    term: 'APK (Android Package Kit)',
    slug: 'apk-android-package-kit',
    definition: 'The packaged file format used to distribute and install Android applications.',
    example: 'To install an app from outside the Google Play Store, you need to download and open its APK file.',
  },
  {
    id: 'app-bundle-aab',
    term: 'App Bundle (AAB)',
    slug: 'app-bundle-aab',
    definition: 'A publishing format that allows Google Play to generate optimized APKs per device configuration.',
    example: 'Developers upload a single AAB to Google Play, which then delivers smaller, optimized APKs to users containing only the resources for their specific screen size and language.',
  },
  {
    id: 'app-sandbox-android',
    term: 'App Sandbox (Android)',
    slug: 'app-sandbox-android',
    definition: 'A security feature isolating apps from one another, protecting data and system integrity.',
    example: 'Because of the app sandbox, a malicious game you installed cannot access the private data stored by your banking app.',
  },
  {
    id: 'application-layer-osi-model',
    term: 'Application Layer (OSI Model)',
    slug: 'application-layer-osi-model',
    definition: 'Layer 7; the closest to the user, enabling HTTP, FTP, SMTP, DNS, etc.',
    example: 'When you use a web browser, you are interacting with protocols at the Application Layer, such as HTTP to request webpages.',
  },
  {
    id: 'application-pool-iis',
    term: 'Application Pool (IIS)',
    slug: 'application-pool-iis',
    definition: 'An isolated environment where web applications run, improving security and stability.',
    example: 'The admin configured each website to run in its own application pool, so if one site crashed, it wouldn\'t bring down the others on the same server.',
  },
  {
    id: 'archive-bit',
    term: 'Archive Bit',
    slug: 'archive-bit',
    definition: 'A file attribute indicating whether the file has been backed up.',
    example: 'Backup software checks the archive bit on files to determine which ones have changed since the last backup and need to be saved again.',
  },
  {
    id: 'arm-architecture',
    term: 'ARM Architecture',
    slug: 'arm-architecture',
    definition: 'A low-power processor instruction set used in mobile, IoT, and some server hardware.',
    example: 'Most smartphones and tablets, including the iPhone and many Android devices, are powered by ARM-based processors due to their energy efficiency.',
  },
  {
    id: 'arp-address-resolution-protocol',
    term: 'ARP (Address Resolution Protocol)',
    slug: 'arp-address-resolution-protocol',
    definition: 'Maps IP addresses to physical MAC addresses on local networks.',
    example: 'When your computer wants to send data to another device on your Wi-Fi, it uses ARP to find the destination device\'s physical MAC address.',
  },
  {
    id: 'artifact-ci-cd',
    term: 'Artifact (CI/CD)',
    slug: 'artifact-ci-cd',
    definition: 'Any output from the build process—executables, libraries, Docker images, bundles.',
    example: 'After a successful build, the CI/CD pipeline stores the compiled .apk file as an artifact, ready for testing and deployment.',
  },
  {
    id: 'asgi-asynchronous-server-gateway-interface',
    term: 'ASGI (Asynchronous Server Gateway Interface)',
    slug: 'asgi-asynchronous-server-gateway-interface',
    definition: 'A Python standard supporting asynchronous web applications (successor to WSGI).',
    example: 'Web frameworks like FastAPI use ASGI to handle many concurrent connections efficiently, making them ideal for applications with WebSockets or long-polling.',
  },
  {
    id: 'asimd-advanced-simd-neon-instructions',
    term: 'ASIMD (Advanced SIMD / Neon Instructions)',
    slug: 'asimd-advanced-simd-neon-instructions',
    definition: 'ARM’s vector processing extension for high-performance parallel computation.',
    example: 'A mobile video editing app uses ASIMD instructions to speed up the process of applying filters to video frames.',
  },
  {
    id: 'asm-js',
    term: 'ASM.js',
    slug: 'asm-js',
    definition: 'A low-level subset of JavaScript designed for high-performance web applications.',
    example: 'Game engines were sometimes compiled to asm.js to run complex 3D graphics in a web browser before WebAssembly became widespread.',
  },
  {
    id: 'asn-1-abstract-syntax-notation-one',
    term: 'ASN.1 (Abstract Syntax Notation One)',
    slug: 'asn-1-abstract-syntax-notation-one',
    definition: 'A schema language used in telecom, cryptography, and networking for encoding structured data.',
    example: 'SSL/TLS certificates use ASN.1 to define the structure of the certificate\'s data, such as the public key and issuer information.',
  },
  {
    id: 'asp-net-core-middleware',
    term: 'ASP.NET Core Middleware',
    slug: 'asp-net-core-middleware',
    definition: 'Components that process HTTP requests/responses in the ASP.NET pipeline.',
    example: 'An ASP.NET developer added a middleware component to log every incoming HTTP request before it reaches the application logic.',
  },
  {
    id: 'asset-pipeline',
    term: 'Asset Pipeline',
    slug: 'asset-pipeline',
    definition: 'A build system for processing static files (CSS, JS, images) into optimized bundles.',
    example: 'The Ruby on Rails asset pipeline automatically combines and minifies all JavaScript files into a single, smaller file to improve page load times.',
  },
  {
    id: 'asymmetric-encryption',
    term: 'Asymmetric Encryption',
    slug: 'asymmetric-encryption',
    definition: 'Cryptography using public and private keys for secure message exchange.',
    example: 'When you send an encrypted email using PGP, you use the recipient\'s public key to encrypt it, and they use their private key to decrypt it.',
  },
  {
    id: 'algorithm',
    term: 'Algorithm',
    slug: 'algorithm',
    definition: 'A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer.',
    example: 'Google\'s search algorithm is a complex system used to retrieve data from its search index and instantly deliver the best possible results for a query.',
  },
  {
    id: 'api',
    term: 'API',
    slug: 'api',
    definition: 'An Application Programming Interface (API) is a set of rules and protocols that allows different software applications to communicate with each other. It defines the methods and data formats that applications can use to request and exchange information.',
    example: 'When you use an app like Uber, it uses Google Maps\' API to show you the map and calculate routes, rather than building its own mapping service from scratch.',
  },
  {
    id: 'authentication',
    term: 'Authentication',
    slug: 'authentication',
    definition: 'The process of verifying the identity of a user or process. It confirms that you are who you say you are.',
    example: 'Entering your username and password on a website is the most common form of authentication.',
  },
  {
    id: 'authorization',
    term: 'Authorization',
    slug: 'authorization',
    definition: 'The process of giving an individual or service permission to do something or have access to specific resources. It happens after authentication.',
    example: 'After you log in (authentication), the system checks your role (authorization) to see if you have permission to view the admin dashboard.',
  },
  {
    id: 'backend',
    term: 'Backend',
    slug: 'backend',
    definition: 'The backend of a website or software application is the part that the user doesn\'t see. It includes the server, database, and application logic. It\'s responsible for storing and organizing data and ensuring everything on the client-side works.',
    example: 'When you sign up for a new account, the backend is what processes your information, creates your user profile, and stores it securely in a database.',
  },
  {
    id: 'backlog',
    term: 'Backlog',
    slug: 'backlog',
    definition: 'In project management, a backlog is a list of tasks or features that need to be completed. In Agile, this is often the product backlog, which is a prioritized list of work for the development team.',
    example: 'The team reviewed the product backlog to decide which features to work on in the next sprint.',
  },
  {
    id: 'bandwidth',
    term: 'Bandwidth',
    slug: 'bandwidth',
    definition: 'The maximum rate of data transfer across a given path. It is often mistaken for internet speed, but it\'s actually the volume of information that can be sent over a connection in a measured amount of time.',
    example: 'Streaming a 4K movie requires more bandwidth than browsing a simple text-based website.',
  },
  {
    id: 'bare-metal',
    term: 'Bare metal',
    slug: 'bare-metal',
    definition: 'A computer server that is a physical piece of hardware, dedicated to a single tenant. The tenant can run their choice of operating system and software directly on the hardware.',
    example: 'For maximum performance, the gaming company decided to run its application on a bare-metal server instead of in a virtualized environment.',
  },
  {
    id: 'bash',
    term: 'Bash',
    slug: 'bash',
    definition: 'A command-line interpreter and scripting language for Unix-like operating systems. It is the default shell for many Linux distributions and for macOS.',
    example: 'The developer wrote a Bash script to automate the process of backing up files every night.',
  },
  {
    id: 'big-data',
    term: 'Big Data',
    slug: 'big-data',
    definition: 'Extremely large and complex datasets that traditional data-processing application software is inadequate to deal with. It is characterized by the three Vs: volume, velocity, and variety.',
    example: 'Social media companies analyze big data to understand user behavior and serve targeted ads.',
  },
  {
    id: 'binary',
    term: 'Binary',
    slug: 'binary',
    definition: 'A number system that only uses two digits: 0 and 1. It is the fundamental language of computers.',
    example: 'The letter "A" is represented in binary as 01000001.',
  },
  {
    id: 'bios',
    term: 'BIOS',
    slug: 'bios',
    definition: 'Basic Input/Output System. Firmware used to perform hardware initialization during the booting process (power-on startup) and to provide runtime services for operating systems and programs.',
    example: 'I had to enter the BIOS to change the boot order of my computer.',
  },
  {
    id: 'bit',
    term: 'Bit',
    slug: 'bit',
    definition: 'The smallest unit of data in a computer, with a single binary value of either 0 or 1.',
    example: 'A 64-bit processor can handle more data at once than a 32-bit processor.',
  },
  {
    id: 'blockchain',
    term: 'Blockchain',
    slug: 'blockchain',
    definition: 'A blockchain is a distributed, immutable ledger that is used to record transactions and track assets in a business network. An asset can be tangible (a house, car, cash, land) or intangible (intellectual property, patents, copyrights, branding).',
    example: 'Bitcoin uses a blockchain to record all transactions. Each "block" contains a list of transactions, and it\'s linked to the previous one, creating a secure and unchangeable chain.',
  },
  {
    id: 'bug',
    term: 'Bug',
    slug: 'bug',
    definition: 'An error, flaw, or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.',
    example: 'The developers worked all night to fix a critical bug before the software release.',
  },
  {
    id: 'build',
    term: 'Build',
    slug: 'build',
    definition: 'In software development, a build is the process of converting source code files into a standalone artifact (like an executable program or a library) that can be run on a computer.',
    example: 'The continuous integration server automatically creates a new build every time a developer pushes code to the repository.',
  },
  {
    id: 'byte',
    term: 'Byte',
    slug: 'byte',
    definition: 'A unit of digital information that most commonly consists of eight bits. It is the basic addressable element in many computer architectures.',
    example: 'A file size is often measured in kilobytes, megabytes, or gigabytes, which are multiples of a byte.',
  },
  {
    id: 'cache',
    term: 'Cache',
    slug: 'cache',
    definition: 'A cache is a temporary storage area that stores data so that future requests for that data can be served faster. It could be a hardware or software component.',
    example: 'Your web browser caches images and text from websites you visit frequently, so the next time you go to that site, it loads much faster because the content is already on your computer.',
  },
  {
    id: 'cdn',
    term: 'CDN',
    slug: 'cdn',
    definition: 'A Content Delivery Network (CDN) is a geographically distributed network of proxy servers and their data centers. The goal is to provide high availability and performance by distributing the service spatially relative to end-users.',
    example: 'Netflix uses a CDN to store copies of its movies and shows on servers all around the world, so when you stream a video, it comes from a server near you, reducing buffering and improving quality.',
  },
  {
    id: 'cli',
    term: 'CLI',
    slug: 'cli',
    definition: 'A Command-Line Interface (CLI) is a text-based interface used to run programs, manage computer files and interact with the computer. It is an alternative to a Graphical User Interface (GUI).',
    example: 'Instead of clicking on icons, a developer might use the CLI to navigate folders, create files, and run programs by typing commands like `cd my-project` or `npm install`.',
  },
  {
    id: 'ci-cd',
    term: 'CI/CD',
    slug: 'ci-cd',
    definition: 'Continuous Integration and Continuous Delivery/Deployment. A method to frequently deliver apps to customers by introducing automation into the stages of app development.',
    example: 'Our team has a CI/CD pipeline that automatically builds, tests, and deploys our application whenever new code is merged.',
  },
  {
    id: 'class',
    term: 'Class',
    slug: 'class',
    definition: 'In object-oriented programming, a class is a blueprint for creating objects. It provides initial values for state (member variables) and implementations of behavior (member functions or methods).',
    example: 'The programmer defined a `Car` class with properties like `color` and `speed`, and methods like `start()` and `stop()`.',
  },
  {
    id: 'cloud-computing',
    term: 'Cloud Computing',
    slug: 'cloud-computing',
    definition: 'The delivery of computing services—including servers, storage, databases, networking, software, analytics, and intelligence—over the Internet ("the cloud") to offer faster innovation, flexible resources, and economies of scale.',
    example: 'Instead of buying and managing their own servers, the startup used Amazon Web Services (AWS) for their cloud computing needs.',
  },
  {
    id: 'codec',
    term: 'Codec',
    slug: 'codec',
    definition: 'A device or program that compresses data to enable faster transmission and decompresses received data. A portmanteau of "coder-decoder".',
    example: 'Video streaming services use codecs like H.264 to compress video files for efficient streaming over the internet.',
  },
  {
    id: 'commit',
    term: 'Commit',
    slug: 'commit',
    definition: 'In version control systems like Git, a commit is the operation which saves the changes to the local repository. Each commit has a unique ID and a message describing the changes.',
    example: 'After fixing the bug, the developer made a commit with the message "Fix login issue for guest users".',
  },
  {
    id: 'compiler',
    term: 'Compiler',
    slug: 'compiler',
    definition: 'A special program that processes statements written in a particular programming language and turns them into machine language or "code" that a computer\'s processor uses.',
    example: 'The C++ code was run through a compiler to create an executable file that could be run on Windows.',
  },
  {
    id: 'containerization',
    term: 'Containerization',
    slug: 'containerization',
    definition: 'A lightweight alternative to full machine virtualization that involves encapsulating an application in a container with its own operating environment.',
    example: 'Docker is a popular tool for containerization, allowing developers to package an application with all its dependencies.',
  },
  {
    id: 'cookie',
    term: 'Cookie',
    slug: 'cookie',
    definition: 'A small piece of data sent from a website and stored on the user\'s computer by the user\'s web browser while the user is browsing.',
    example: 'An e-commerce site uses a cookie to remember the items you added to your shopping cart.',
  },
  {
    id: 'cpu',
    term: 'CPU',
    slug: 'cpu',
    definition: 'Central Processing Unit. The primary component of a computer that executes instructions. It is often referred to as the "brain" of the computer.',
    example: 'A faster CPU can improve the performance of a computer, especially for intensive tasks like video editing or gaming.',
  },
  {
    id: 'cron-job',
    term: 'Cron job',
    slug: 'cron-job',
    definition: 'A time-based job scheduler in Unix-like computer operating systems. Users who set up and maintain software environments use cron to schedule jobs to run periodically at fixed times, dates, or intervals.',
    example: 'The system administrator set up a cron job to perform a database backup every day at 2 AM.',
  },
  {
    id: 'cross-site-scripting',
    term: 'Cross-Site Scripting (XSS)',
    slug: 'cross-site-scripting',
    definition: 'A type of security vulnerability typically found in web applications. XSS allows attackers to inject client-side scripts into web pages viewed by other users.',
    example: 'The website was vulnerable to XSS, allowing an attacker to steal users\' session cookies by injecting a malicious script into the comment section.',
  },
  {
    id: 'cryptography',
    term: 'Cryptography',
    slug: 'cryptography',
    definition: 'The practice and study of techniques for secure communication in the presence of third parties called adversaries. It is about constructing and analyzing protocols that prevent third parties or the public from reading private messages.',
    example: 'End-to-end encryption in messaging apps is a modern application of cryptography.',
  },
  {
    id: 'css',
    term: 'CSS',
    slug: 'css',
    definition: 'Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language like HTML. CSS describes how HTML elements should be displayed on screen, paper, or in other media.',
    example: 'If HTML is the skeleton of a webpage, CSS is the clothing. It defines the colors, fonts, and layout, making the website visually appealing.',
  },
  {
    id: 'daemon',
    term: 'Daemon',
    slug: 'daemon',
    definition: 'A computer program that runs as a background process, rather than being under the direct control of an interactive user.',
    example: 'The `sshd` daemon on a Linux server listens for incoming SSH connections.',
  },
  {
    id: 'data-lake',
    term: 'Data Lake',
    slug: 'data-lake',
    definition: 'A centralized repository that allows you to store all your structured and unstructured data at any scale.',
    example: 'The company built a data lake to store raw data from IoT devices, social media, and sales transactions for future analysis.',
  },
  {
    id: 'data-mining',
    term: 'Data Mining',
    slug: 'data-mining',
    definition: 'The process of discovering patterns in large data sets involving methods at the intersection of machine learning, statistics, and database systems.',
    example: 'Retail companies use data mining to discover customer shopping habits and offer personalized recommendations.',
  },
  {
    id: 'data-warehouse',
    term: 'Data Warehouse',
    slug: 'data-warehouse',
    definition: 'A large store of data accumulated from a wide range of sources within a company and used to guide management decisions. The data is typically structured and cleaned for reporting and analysis.',
    example: 'Analysts query the data warehouse to generate reports on quarterly sales performance across different regions.',
  },
  {
    id: 'database',
    term: 'Database',
    slug: 'database',
    definition: 'A database is an organized collection of structured information, or data, typically stored electronically in a computer system. A database is usually controlled by a database management system (DBMS).',
    example: 'A social media app stores all user profiles, posts, comments, and likes in a database, allowing the information to be retrieved and displayed to users.',
  },
  {
    id: 'debug',
    term: 'Debug',
    slug: 'debug',
    definition: 'The process of finding and resolving defects or problems within a computer program that prevent correct operation of computer software or a system.',
    example: 'The programmer spent hours debugging the code to find the source of the crash.',
  },
  {
    id: 'deployment',
    term: 'Deployment',
    slug: 'deployment',
    definition: 'In software development, deployment is the process of making a software application available for use. This can involve installing the software on servers, configuring it, and making it accessible to users.',
    example: 'After months of development, the team began the deployment process to push the new version of their website to the live servers for everyone to see.',
  },
  {
    id: 'devops',
    term: 'DevOps',
    slug: 'devops',
    definition: 'A set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the systems development life cycle and provide continuous delivery with high software quality.',
    example: 'By adopting a DevOps culture, the company was able to release software updates much faster and with fewer errors.',
  },
  {
    id: 'dhcp',
    term: 'DHCP',
    slug: 'dhcp',
    definition: 'Dynamic Host Configuration Protocol. A network management protocol used to automate the process of configuring devices on IP networks.',
    example: 'When you connect to a Wi-Fi network, your device gets an IP address automatically from a DHCP server.',
  },
  {
    id: 'dns',
    term: 'DNS',
    slug: 'dns',
    definition: 'The Domain Name System (DNS) is the phonebook of the Internet. Humans access information online through domain names, like nytimes.com or espn.com. Web browsers interact through Internet Protocol (IP) addresses. DNS translates domain names to IP addresses so browsers can load Internet resources.',
    example: 'When you type "google.com" into your browser, DNS servers find the correct IP address for Google, like 172.217.9.142, allowing your computer to connect to it.',
  },
  {
    id: 'docker',
    term: 'Docker',
    slug: 'docker',
    definition: 'Docker is a platform for developing, shipping, and running applications in containers. It allows developers to package an application with all of its dependencies into a standardized unit for software development.',
    example: 'A developer uses Docker to create a container with their web application, a database, and all necessary libraries. They can then share this single container with their team, ensuring it runs exactly the same for everyone.',
  },
  {
    id: 'dom',
    term: 'DOM',
    slug: 'dom',
    definition: 'Document Object Model. A programming interface for web documents. It represents the page so that programs can change the document structure, style, and content.',
    example: 'JavaScript uses the DOM to manipulate HTML elements, like changing the text of a paragraph or adding a new button.',
  },
  {
    id: 'downtime',
    term: 'Downtime',
    slug: 'downtime',
    definition: 'A period of time when a system, such as a computer or a network, is unavailable or out of service.',
    example: 'The website experienced some downtime last night for scheduled maintenance.',
  },
  {
    id: 'edge-computing',
    term: 'Edge Computing',
    slug: 'edge-computing',
    definition: 'A distributed computing paradigm that brings computation and data storage closer to the sources of data. This is done to improve response times and save bandwidth.',
    example: 'A smart security camera might use edge computing to process video locally and only send an alert to the cloud if it detects motion.',
  },
  {
    id: 'emulator',
    term: 'Emulator',
    slug: 'emulator',
    definition: 'Hardware or software that enables one computer system (called the host) to behave like another computer system (called the guest).',
    example: 'A developer uses an Android emulator on their computer to test how their app will look and behave on a real phone.',
  },
  {
    id: 'encapsulation',
    term: 'Encapsulation',
    slug: 'encapsulation',
    definition: 'In object-oriented programming, encapsulation refers to the bundling of data with the methods that operate on that data, or the restricting of direct access to some of an object\'s components.',
    example: 'A `Car` class encapsulates the `speed` variable, only allowing it to be changed through methods like `accelerate()` and `brake()`.',
  },
  {
    id: 'encryption',
    term: 'Encryption',
    slug: 'encryption',
    definition: 'Encryption is the process of converting information or data into a code, especially to prevent unauthorized access. The reverse process, decryption, makes the encrypted information readable again.',
    example: 'Messaging apps like Signal use end-to-end encryption to scramble your messages, so only you and the person you\'re communicating with can read them.',
  },
  {
    id: 'endpoint',
    term: 'Endpoint',
    slug: 'endpoint',
    definition: 'In an API, an endpoint is one end of a communication channel. It refers to a specific URL where an API can be accessed by a client application.',
    example: 'To get user information, the app sends a request to the `/api/users/{userId}` endpoint.',
  },
  {
    id: 'etl',
    term: 'ETL',
    slug: 'etl',
    definition: 'Extract, Transform, Load. A type of data integration that refers to the three steps (extract, transform, load) used to blend data from multiple sources.',
    example: 'The company uses an ETL process to pull sales data from various stores, convert it into a standard format, and load it into the central data warehouse.',
  },
  {
    id: 'firewall',
    term: 'Firewall',
    slug: 'firewall',
    definition: 'A firewall is a network security device that monitors incoming and outgoing network traffic and decides whether to allow or block specific traffic based on a defined set of security rules.',
    example: 'Your home internet router has a built-in firewall that acts like a security guard, preventing unauthorized access to your home network from the internet.',
  },
  {
    id: 'firmware',
    term: 'Firmware',
    slug: 'firmware',
    definition: 'A specific class of computer software that provides low-level control for a device\'s specific hardware.',
    example: 'You might need to update the firmware on your router to get new features or security patches.',
  },
  {
    id: 'framework',
    term: 'Framework',
    slug: 'framework',
    definition: 'A pre-written set of code that provides a structure for developing software applications. It provides a standard way to build and deploy applications.',
    example: 'React and Angular are popular JavaScript frameworks for building user interfaces.',
  },
  {
    id: 'frontend',
    term: 'Frontend',
    slug: 'frontend',
    definition: 'The frontend of a website or software application is the part that the user interacts with directly. It is also referred to as the "client-side" of the application. It includes everything that users experience directly: text colors and styles, images, graphs and tables, buttons, colors, and navigation menu.',
    example: 'A frontend developer uses HTML, CSS, and JavaScript to build the visual elements of a website, like the sign-up form, the navigation bar, and the layout of the articles you read.',
  },
  {
    id: 'full-stack',
    term: 'Full-stack',
    slug: 'full-stack',
    definition: 'A full-stack developer is an engineer who can handle all the work of databases, servers, systems engineering, and clients. Depending on the project, what customers need may be a mobile stack, a Web stack, or a native application stack.',
    example: 'The startup hired a full-stack developer who could build both the user-facing website and the server-side logic to power it.',
  },
  {
    id: 'garbage-collection',
    term: 'Garbage Collection',
    slug: 'garbage-collection',
    definition: 'A form of automatic memory management. The garbage collector attempts to reclaim memory that was allocated by the program, but is no longer referenced.',
    example: 'Languages like Java and C# have automatic garbage collection, which frees developers from manually managing memory.',
  },
  {
    id: 'gateway',
    term: 'Gateway',
    slug: 'gateway',
    definition: 'A node (router) on a TCP/IP network that serves as an access point to another network. A gateway is a networking hardware device that connects two dissimilar networks.',
    example: 'Your home router acts as a gateway between your local network (LAN) and the internet (WAN).',
  },
  {
    id: 'git',
    term: 'Git',
    slug: 'git',
    definition: 'Git is a distributed version control system designed to handle everything from small to very large projects with speed and efficiency. It is used for tracking changes in source code during software development.',
    example: 'A team of developers uses Git to work on the same project. Each developer can work on their own "branch" and then merge their changes back into the main project, while Git keeps track of every change made.',
  },
  {
    id: 'gpu',
    term: 'GPU',
    slug: 'gpu',
    definition: 'Graphics Processing Unit. A specialized electronic circuit designed to rapidly manipulate and alter memory to accelerate the creation of images in a frame buffer intended for output to a display device.',
    example: 'A powerful GPU is essential for playing modern video games at high settings and for training complex machine learning models.',
  },
  {
    id: 'graphql',
    term: 'GraphQL',
    slug: 'graphql',
    definition: 'GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. It gives clients the power to ask for exactly what they need and nothing more, making it easier to evolve APIs over time.',
    example: 'Instead of making multiple API requests to get a user\'s profile, their posts, and their followers, a mobile app can use a single GraphQL query to fetch all of that specific data at once.',
  },
  {
    id: 'gui',
    term: 'GUI',
    slug: 'gui',
    definition: 'Graphical User Interface. A type of user interface that allows users to interact with electronic devices through graphical icons and audio indicators such as primary notation, instead of text-based user interfaces, typed command labels or text navigation.',
    example: 'Windows and macOS have sophisticated GUIs, making them easy for most people to use.',
  },
  {
    id: 'html',
    term: 'HTML',
    slug: 'html',
    definition: 'HyperText Markup Language (HTML) is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.',
    example: 'HTML provides the basic structure of a webpage, like creating headings, paragraphs, and links, much like a skeleton provides the frame for a body.',
  },
  {
    id: 'http',
    term: 'HTTP/HTTPS',
    slug: 'http',
    definition: 'Hypertext Transfer Protocol (HTTP) is the foundation of data communication for the World Wide Web. HTTPS is the secure version of HTTP, where communications are encrypted.',
    example: 'When you visit a website, your browser sends an HTTP request to the server to get the page content. If you\'re on a banking site, it uses HTTPS to encrypt your login details for security.',
  },
  {
    id: 'ide',
    term: 'IDE',
    slug: 'ide',
    definition: 'An Integrated Development Environment (IDE) is a software application that provides comprehensive facilities to computer programmers for software development. An IDE normally consists of a source code editor, build automation tools, and a debugger.',
    example: 'Programmers use an IDE like Visual Studio Code, which combines a code editor, a terminal, and debugging tools all in one window to streamline their workflow.',
  },
  {
    id: 'immutable',
    term: 'Immutable',
    slug: 'immutable',
    definition: 'An object whose state cannot be modified after it is created. This is in contrast to a mutable object, which can be modified after it is created.',
    example: 'In many programming languages, strings are immutable. Any function that seems to modify a string actually creates a new one.',
  },
  {
    id: 'inheritance',
    term: 'Inheritance',
    slug: 'inheritance',
    definition: 'In object-oriented programming, inheritance is the mechanism of basing an object or class upon another object (prototype-based inheritance) or class (class-based inheritance), retaining similar implementation.',
    example: 'A `Dog` class and a `Cat` class can both inherit properties and methods from a more general `Animal` class.',
  },
  {
    id: 'integration-testing',
    term: 'Integration Testing',
    slug: 'integration-testing',
    definition: 'A level of software testing where individual units are combined and tested as a group. The purpose of this level of testing is to expose faults in the interaction between integrated units.',
    example: 'After unit testing the login and database modules, the team performed integration testing to ensure they worked together correctly.',
  },
  {
    id: 'iot',
    term: 'IoT',
    slug: 'iot',
    definition: 'Internet of Things. The network of physical devices, vehicles, home appliances and other items embedded with electronics, software, sensors, actuators, and connectivity which enables these objects to connect and exchange data.',
    example: 'Smart home devices like thermostats, lights, and speakers are all part of the IoT.',
  },
  {
    id: 'ip-address',
    term: 'IP Address',
    slug: 'ip-address',
    definition: 'An Internet Protocol (IP) address is a numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication. An IP address serves two main functions: host or network interface identification and location addressing.',
    example: 'An IP address is like the mailing address for your computer on the internet, allowing it to send and receive data from other computers.',
  },
  {
    id: 'javascript',
    term: 'JavaScript',
    slug: 'javascript',
    definition: 'JavaScript is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. It enables interactive web pages and is an essential part of web applications.',
    example: 'When you click a button on a website and a pop-up appears without the page reloading, that interactivity is powered by JavaScript.',
  },
  {
    id: 'json',
    term: 'JSON',
    slug: 'json',
    definition: 'JavaScript Object Notation (JSON) is a lightweight data-interchange format. It is easy for humans to read and write and easy for machines to parse and generate. It is based on a subset of the JavaScript Programming Language.',
    example: 'When a weather app gets forecast data from a server, the server often sends it in JSON format, like {"city": "New York", "temperature": 75}, which the app can easily understand and display.',
  },
  {
    id: 'jwt',
    term: 'JWT',
    slug: 'jwt',
    definition: 'JSON Web Token. A compact, URL-safe means of representing claims to be transferred between two parties. The claims in a JWT are encoded as a JSON object that is used as the payload of a JSON Web Signature (JWS) structure or as the plaintext of a JSON Web Encryption (JWE) structure.',
    example: 'After a user logs in, the server issues a JWT which the client then sends with every subsequent request to prove they are authenticated.',
  },
  {
    id: 'kernel',
    term: 'Kernel',
    slug: 'kernel',
    definition: 'The core component of an operating system. It manages the system\'s resources, and it is a bridge between the hardware and the software.',
    example: 'The Linux kernel is open-source, meaning anyone can view and contribute to its code.',
  },
  {
    id: 'kubernetes',
    term: 'Kubernetes',
    slug: 'kubernetes',
    definition: 'Kubernetes, also known as K8s, is an open-source system for automating deployment, scaling, and management of containerized applications.',
    example: 'A large e-commerce site uses Kubernetes to manage its thousands of microservices. If one service fails, Kubernetes automatically restarts it. If traffic surges during a sale, it automatically scales up the necessary services.',
  },
  {
    id: 'lan',
    term: 'LAN',
    slug: 'lan',
    definition: 'A Local Area Network (LAN) is a collection of devices connected together in one physical location, such as a building, office, or home. A LAN can be small or large, ranging from a home network with one user to an enterprise network with thousands of users and devices in an office or school.',
    example: 'The computers, printers, and smart devices connected to your home Wi-Fi network form a LAN.',
  },
  {
    id: 'latency',
    term: 'Latency',
    slug: 'latency',
    definition: 'The delay before a transfer of data begins following an instruction for its transfer. In networking, it\'s the time it takes for a data packet to travel from one point to another.',
    example: 'Online gamers prefer a connection with low latency to avoid lag between their actions and what happens in the game.',
  },
  {
    id: 'library',
    term: 'Library',
    slug: 'library',
    definition: 'In programming, a library is a collection of pre-compiled routines that a program can use. The routines, sometimes called modules, are stored in object format.',
    example: 'Instead of writing their own code to handle dates and times, the developer used the `date-fns` library.',
  },
  {
    id: 'load-balancing',
    term: 'Load Balancing',
    slug: 'load-balancing',
    definition: 'The process of distributing network traffic or computational workloads across multiple servers to ensure no single server becomes overwhelmed. It improves responsiveness and availability of applications.',
    example: 'A busy website uses a load balancer to distribute incoming traffic evenly across a fleet of web servers.',
  },
  {
    id: 'log',
    term: 'Log',
    slug: 'log',
    definition: 'A file that records either events that occur in an operating system or other software runs, or messages between different users of a communication software.',
    example: 'When the application crashed, the developer checked the error log to find the cause of the problem.',
  },
  {
    id: 'machine-learning',
    term: 'Machine Learning',
    slug: 'machine-learning',
    definition: 'Machine learning is a branch of artificial intelligence (AI) and computer science which focuses on the use of data and algorithms to imitate the way that humans learn, gradually improving its accuracy.',
    example: 'Your email service uses machine learning to identify spam by learning from the emails you and other users mark as junk.',
  },
  {
    id: 'middleware',
    term: 'Middleware',
    slug: 'middleware',
    definition: 'Software that acts as a bridge between an operating system or database and applications, especially on a network.',
    example: 'In our web application, we have middleware that checks if a user is authenticated before allowing them to access certain routes.',
  },
  {
    id: 'microservices',
    term: 'Microservices',
    slug: 'microservices',
    definition: 'Microservices is an architectural style that structures an application as a collection of loosely coupled services. In a microservices architecture, services are fine-grained and the protocols are lightweight.',
    example: 'An online shopping application might be built using microservices: one service for user accounts, another for the product catalog, and a third for the shopping cart. They all work together but can be updated independently.',
  },
  {
    id: 'monorepo',
    term: 'Monorepo',
    slug: 'monorepo',
    definition: 'A software development strategy where code for many projects is stored in the same repository.',
    example: 'Google uses a massive monorepo to manage the source code for nearly all of its software.',
  },
  {
    id: 'mvc',
    term: 'MVC',
    slug: 'mvc',
    definition: 'Model-View-Controller. An architectural pattern that separates an application into three main logical components: the model, the view, and the controller.',
    example: 'Many web frameworks, like Ruby on Rails, are based on the MVC pattern to organize code.',
  },
  {
    id: 'nosql',
    term: 'NoSQL',
    slug: 'nosql',
    definition: 'A NoSQL database provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases. They are highly flexible and can handle large amounts of unstructured data.',
    example: 'A social media platform uses a NoSQL database to store user posts, which can vary greatly in structure—some have text, some have images, some have videos, making a flexible data model ideal.',
  },
  {
    id: 'npm',
    term: 'npm',
    slug: 'npm',
    definition: 'Node Package Manager. It is the default package manager for the JavaScript runtime environment Node.js.',
    example: 'To use the React framework, you first install it into your project by running `npm install react`.',
  },
  {
    id: 'oauth',
    term: 'OAuth',
    slug: 'oauth',
    definition: 'OAuth is an open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.',
    example: 'When you see a "Log in with Google" button on a website, it uses OAuth. You grant that site access to your basic Google profile information without ever giving it your Google password.',
  },
  {
    id: 'object-oriented-programming',
    term: 'Object-Oriented Programming (OOP)',
    slug: 'object-oriented-programming',
    definition: 'A programming paradigm based on the concept of "objects", which can contain data, in the form of fields (often known as attributes or properties), and code, in the form of procedures (often known as methods).',
    example: 'Java, Python, and C++ are popular object-oriented programming languages.',
  },
  {
    id: 'open-source',
    term: 'Open Source',
    slug: 'open-source',
    definition: 'Software for which the original source code is made freely available and may be redistributed and modified.',
    example: 'The Linux operating system is one of the most successful examples of open-source software.',
  },
  {
    id: 'paas',
    term: 'PaaS',
    slug: 'paas',
    definition: 'Platform as a Service (PaaS) is a cloud computing model where a third-party provider delivers hardware and software tools to users over the internet. PaaS provides a platform for developers to build, run, and manage applications without the complexity of building and maintaining the infrastructure.',
    example: 'A developer uses a PaaS like Heroku to deploy their web application. They just upload their code, and Heroku handles the servers, databases, and scaling, letting the developer focus only on the app itself.',
  },
  {
    id: 'packet',
    term: 'Packet',
    slug: 'packet',
    definition: 'A small amount of data sent over a network, such as a LAN or the Internet. Each packet contains the address of its origin and destination, and information that connects it to the other packets in the message.',
    example: 'When you load a webpage, its content is broken down into many small packets that are sent to your computer and reassembled by your browser.',
  },
  {
    id: 'polymorphism',
    term: 'Polymorphism',
    slug: 'polymorphism',
    definition: 'In programming, polymorphism is the provision of a single interface to entities of different types. It allows you to perform a single action in different ways.',
    example: 'A `shape.draw()` method could be used on a `Circle` object to draw a circle, and on a `Square` object to draw a square, demonstrating polymorphism.',
  },
  {
    id: 'port',
    term: 'Port',
    slug: 'port',
    definition: 'In computer networking, a port is a communication endpoint. It is a number used to identify a specific process to which a network message is to be forwarded when it arrives at a server.',
    example: 'Web servers typically listen for HTTP traffic on port 80 and HTTPS traffic on port 443.',
  },
  {
    id: 'protocol',
    term: 'Protocol',
    slug: 'protocol',
    definition: 'A set of rules or procedures for transmitting data between electronic devices, such as computers.',
    example: 'HTTP is the protocol used for transmitting webpages, while SMTP is the protocol for sending emails.',
  },
  {
    id: 'proxy',
    term: 'Proxy',
    slug: 'proxy',
    definition: 'A proxy server is a server application that acts as an intermediary between a client requesting a resource and the server providing that resource.',
    example: 'A company might use a proxy server to filter and monitor its employees\' internet traffic.',
  },
  {
    id: 'pull-request',
    term: 'Pull Request (PR)',
    slug: 'pull-request',
    definition: 'A feature of version control systems (like GitHub) that allows a developer to propose changes to a codebase. It is a request for the repository maintainers to "pull" the developer\'s changes into the main branch.',
    example: 'After finishing the new feature, the developer opened a pull request for the team to review her code.',
  },
  {
    id: 'query',
    term: 'Query',
    slug: 'query',
    definition: 'A query is a request for data or information from a database. Queries can be designed to retrieve specific data, perform calculations, or automate data management tasks.',
    example: 'When you search for products on an e-commerce website, a query is sent to the database to retrieve all items that match your search criteria.',
  },
  {
    id: 'ram',
    term: 'RAM',
    slug: 'ram',
    definition: 'Random Access Memory. A form of computer memory that can be read and changed in any order, typically used to store working data and machine code.',
    example: 'Having more RAM allows you to have more applications open at the same time without slowing down your computer.',
  },
  {
    id: 'refactoring',
    term: 'Refactoring',
    slug: 'refactoring',
    definition: 'The process of restructuring existing computer code—changing the factoring—without changing its external behavior. The goal is to improve code readability and reduce complexity.',
    example: 'The team decided to refactor the old code to make it more efficient and easier to maintain.',
  },
  {
    id: 'regression-testing',
    term: 'Regression Testing',
    slug: 'regression-testing',
    definition: 'A type of software testing which verifies that a recent program or code change has not adversely affected existing features.',
    example: 'After every new build, an automated suite of regression tests is run to ensure that old bugs haven\'t reappeared.',
  },
  {
    id: 'repository',
    term: 'Repository (Repo)',
    slug: 'repository',
    definition: 'A central location in which data is stored and managed. In software development, a repository (or "repo") is a storage location for software packages, often managed by a version control system like Git.',
    example: 'The project\'s source code is stored in a public GitHub repository.',
  },
  {
    id: 'rest',
    term: 'REST',
    slug: 'rest',
    definition: 'Representational State Transfer (REST) is a software architectural style that defines a set of constraints to be used for creating Web services. Web services that conform to the REST architectural style, called RESTful Web services, provide interoperability between computer systems on the Internet.',
    example: 'Many APIs are RESTful. For example, a weather application might send a request to a URL like `api.weather.com/v1/forecast/new-york` to get the weather, which is a simple, stateless RESTful interaction.',
  },
  {
    id: 'router',
    term: 'Router',
    slug: 'router',
    definition: 'A networking device that forwards data packets between computer networks. Routers perform the traffic directing functions on the Internet.',
    example: 'Your home Wi-Fi router connects your devices to the internet.',
  },
  {
    id: 'saas',
    term: 'SaaS',
    slug: 'saas',
    definition: 'Software as a Service (SaaS) is a software distribution model in which a third-party provider hosts applications and makes them available to customers over the Internet. SaaS is one of three main categories of cloud computing, alongside infrastructure as a service (IaaS) and platform as a service (PaaS).',
    example: 'Web-based email services like Gmail, office tools like Google Docs, or customer relationship management software like Salesforce are all examples of SaaS.',
  },
  {
    id: 'scalability',
    term: 'Scalability',
    slug: 'scalability',
    definition: 'The property of a system to handle a growing amount of work by adding resources to the system.',
    example: 'The application was designed for scalability, allowing it to handle a sudden surge in traffic by automatically adding more servers.',
  },
  {
    id: 'sdk',
    term: 'SDK',
    slug: 'sdk',
    definition: 'A Software Development Kit (SDK) is a collection of software development tools in one installable package. They facilitate the creation of applications by having a compiler, debugger and sometimes a software framework.',
    example: 'To build an Android app, developers download the Android SDK, which includes all the libraries and tools needed to write, test, and debug applications for the Android platform.',
  },
  {
    id: 'server',
    term: 'Server',
    slug: 'server',
    definition: 'A computer program or a device that provides functionality for other programs or devices, called "clients". This architecture is called the client–server model.',
    example: 'When you visit a website, your browser (the client) requests the webpage from a web server.',
  },
  {
    id: 'serverless',
    term: 'Serverless',
    slug: 'serverless',
    definition: 'A cloud-computing execution model in which the cloud provider runs the server, and dynamically manages the allocation of machine resources. Pricing is based on the actual amount of resources consumed by an application, rather than on pre-purchased units of capacity.',
    example: 'The developer used a serverless architecture with AWS Lambda, so she only paid for the compute time she consumed, without needing to manage any servers.',
  },
  {
    id: 'shell',
    term: 'Shell',
    slug: 'shell',
    definition: 'A user interface for access to an operating system\'s services. In general, operating system shells use either a command-line interface (CLI) or graphical user interface (GUI).',
    example: 'Bash is a popular command-line shell used in many Unix-like systems.',
  },
  {
    id: 'sprint',
    term: 'Sprint',
    slug: 'sprint',
    definition: 'In Agile software development, a sprint is a set period of time during which specific work has to be completed and made ready for review. Sprints are typically one to four weeks long.',
    example: 'The development team planned to complete the user authentication feature during the next two-week sprint.',
  },
  {
    id: 'sql',
    term: 'SQL',
    slug: 'sql',
    definition: 'Structured Query Language (SQL) is a standard language for storing, manipulating and retrieving data in relational databases. It is the standard language for Relational Database Management Systems (RDBMS).',
    example: 'A data analyst writes an SQL query like `SELECT * FROM Customers WHERE Country="Mexico";` to retrieve a list of all customers from Mexico from the company\'s database.',
  },
  {
    id: 'ssh',
    term: 'SSH',
    slug: 'ssh',
    definition: 'Secure Shell or Secure Socket Shell. A network protocol that gives users, particularly system administrators, a secure way to access a computer over an unsecured network.',
    example: 'The developer used SSH to securely connect to the remote server and manage its files.',
  },
  {
    id: 'ssl-tls',
    term: 'SSL/TLS',
    slug: 'ssl-tls',
    definition: 'Transport Layer Security (TLS), and its now-deprecated predecessor, Secure Sockets Layer (SSL), are cryptographic protocols designed to provide communications security over a computer network. They are used in applications such as web browsing, email, and instant messaging.',
    example: 'The "https" and padlock icon in your browser\'s address bar indicate that your connection to the website is secured by SSL/TLS, encrypting the data between you and the server.',
  },
  {
    id: 'stack',
    term: 'Stack',
    slug: 'stack',
    definition: 'In software development, a stack is the set of technologies used to build an application. For example, a web stack might include a specific operating system, web server, database, and programming language.',
    example: 'The MERN stack consists of MongoDB, Express.js, React, and Node.js.',
  },
  {
    id: 'tcp-ip',
    term: 'TCP/IP',
    slug: 'tcp-ip',
    definition: 'Transmission Control Protocol/Internet Protocol (TCP/IP) is a suite of communication protocols used to interconnect network devices on the internet. It specifies how data should be packetized, addressed, transmitted, routed, and received.',
    example: 'TCP/IP is the fundamental language of the internet. When you send an email, TCP breaks it into small packets, and IP makes sure they are sent to the correct address, where TCP reassembles them.',
  },
  {
    id: 'throughput',
    term: 'Throughput',
    slug: 'throughput',
    definition: 'The amount of material or items passing through a system or process. In networking, it is the rate of successful message delivery over a communication channel.',
    example: 'We measured the network\'s throughput to see how much data we could actually transfer per second.',
  },
  {
    id: 'token',
    term: 'Token',
    slug: 'token',
    definition: 'In authentication, a token is a piece of data that represents a user\'s identity and is used to access protected resources.',
    example: 'After logging in, the server gives the client an access token to use for future API requests.',
  },
  {
    id: 'ui',
    term: 'UI',
    slug: 'ui',
    definition: 'The User Interface (UI) is the point of human-computer interaction and communication in a device. This can include display screens, keyboards, a mouse, and the appearance of a desktop. It is also the way through which a user interacts with an application or a website.',
    example: 'The UI of a mobile app includes all the buttons you tap, the text you read, the images you see, and the way you swipe through different screens.',
  },
  {
    id: 'unit-testing',
    term: 'Unit Testing',
    slug: 'unit-testing',
    definition: 'A level of software testing where individual units/components of a software are tested. The purpose is to validate that each unit of the software performs as designed.',
    example: 'The developer wrote a unit test for the function that calculates sales tax to ensure it returned the correct amount.',
  },
  {
    id: 'uptime',
    term: 'Uptime',
    slug: 'uptime',
    definition: 'A measure of the time a machine, typically a computer, has been left running and operational. It is often used as a measure of computer operating system reliability or stability.',
    example: 'The server has an uptime of 99.999%, meaning it is almost never down.',
  },
  {
    id: 'url',
    term: 'URL',
    slug: 'url',
    definition: 'Uniform Resource Locator. A reference (an address) to a resource on the Internet. A URL has two main components: a protocol identifier and a resource name.',
    example: 'To visit the Google homepage, you type its URL, `https://www.google.com`, into your browser\'s address bar.',
  },
  {
    id: 'ux',
    term: 'UX',
    slug: 'ux',
    definition: 'User Experience (UX) refers to a person\'s emotions and attitudes about using a particular product, system or service. It includes the practical, experiential, affective, meaningful and valuable aspects of human-computer interaction and product ownership.',
    example: 'A good UX design for an e-commerce site means the process of finding a product, adding it to the cart, and checking out is smooth, intuitive, and frustration-free for the user.',
  },
  {
    id: 'version-control',
    term: 'Version Control',
    slug: 'version-control',
    definition: 'A system that records changes to a file or set of files over time so that you can recall specific versions later.',
    example: 'Git is the most popular version control system, allowing teams to track changes in their code and collaborate effectively.',
  },
  {
    id: 'virtual-machine',
    term: 'Virtual Machine',
    slug: 'virtual-machine',
    definition: 'A Virtual Machine (VM) is a digital version of a physical computer. A VM is a computer file, typically called an image, that behaves like an actual computer. It can run in a window as a separate computing environment, often to run a different operating system.',
    example: 'A developer might use a virtual machine on their Mac to run a full version of Windows, allowing them to test their software on both operating systems without needing a second computer.',
  },
  {
    id: 'vpn',
    term: 'VPN',
    slug: 'vpn',
    definition: 'A Virtual Private Network (VPN) extends a private network across a public network and enables users to send and receive data across shared or public networks as if their computing devices were directly connected to the private network.',
    example: 'An employee working from home uses a VPN to securely connect to their company\'s internal network, allowing them to access files and systems as if they were in the office.',
  },
  {
    id: 'wan',
    term: 'WAN',
    slug: 'wan',
    definition: 'A Wide Area Network (WAN) is a telecommunications network that extends over a large geographic area for the primary purpose of computer networking. WANs are often established with leased telecommunication circuits.',
    example: 'The Internet is the largest WAN, connecting billions of computers globally. A large corporation also uses a WAN to connect its office branches in different cities.',
  },
  {
    id: 'waterfall-model',
    term: 'Waterfall Model',
    slug: 'waterfall-model',
    definition: 'A sequential design process, used in software development processes, in which progress is seen as flowing steadily downwards (like a waterfall) through the phases of conception, initiation, analysis, design, construction, testing, deployment and maintenance.',
    example: 'The project was managed using the Waterfall model, with each phase being completed before the next one began.',
  },
  {
    id: 'websocket',
    term: 'WebSocket',
    slug: 'websocket',
    definition: 'A computer communications protocol, providing full-duplex communication channels over a single TCP connection. It is located at layer 7 in the OSI model and is used for creating real-time applications.',
    example: 'A live chat application uses WebSockets to instantly push new messages to all connected users.',
  },
  {
    id: 'xml',
    term: 'XML',
    slug: 'xml',
    definition: 'Extensible Markup Language (XML) is a markup language and file format for storing, transmitting, and reconstructing arbitrary data. It defines a set of rules for encoding documents in a format that is both human-readable and machine-readable.',
    example: 'XML is often used for configuration files or for transmitting data between different systems. For example, an RSS feed uses an XML file to list the latest articles from a website.',
  },
  {
    id: 'yaml',
    term: 'YAML',
    slug: 'yaml',
    definition: 'YAML (YAML Ain\'t Markup Language) is a human-readable data-serialization language. It is commonly used for configuration files and in applications where data is being stored or transmitted.',
    example: 'Many modern applications use YAML for their configuration files because its syntax is clean and easy to read, using indentation to denote structure, e.g. `docker-compose.yml` or Kubernetes configs.',
  },
  {
    id: 'zip',
    term: 'ZIP',
    slug: 'zip',
    definition: 'ZIP is an archive file format that supports lossless data compression. A .zip file may contain one or more files or directories that may have been compressed. It is a common way to package and transport files.',
    example: 'To send a folder of photos via email, you might first compress it into a single .zip file to reduce the overall size and make it a single attachment.',
  },
];
