export type Term = {
  id: string;
  term: string;
  slug: string;
  definition: string;
  example: string;
};

export const terms: Term[] = [
  {
    id: 'agile',
    term: 'Agile',
    slug: 'agile',
    definition: 'A project management methodology that uses an incremental, iterative approach. Instead of a big-bang launch, teams deliver work in small, but consumable, increments. The goal is to provide value to customers faster and with fewer headaches.',
    example: 'A software team uses the Agile method, working in two-week "sprints" to release new features incrementally, gathering feedback after each release to guide the next phase of development.',
  },
  {
    id: 'api',
    term: 'API',
    slug: 'api',
    definition: 'An Application Programming Interface (API) is a set of rules and protocols that allows different software applications to communicate with each other. It defines the methods and data formats that applications can use to request and exchange information.',
    example: 'When you use an app like Uber, it uses Google Maps\' API to show you the map and calculate routes, rather than building its own mapping service from scratch.',
  },
  {
    id: 'backend',
    term: 'Backend',
    slug: 'backend',
    definition: 'The backend of a website or software application is the part that the user doesn\'t see. It includes the server, database, and application logic. It\'s responsible for storing and organizing data and ensuring everything on the client-side works.',
    example: 'When you sign up for a new account, the backend is what processes your information, creates your user profile, and stores it securely in a database.',
  },
  {
    id: 'blockchain',
    term: 'Blockchain',
    slug: 'blockchain',
    definition: 'A blockchain is a distributed, immutable ledger that is used to record transactions and track assets in a business network. An asset can be tangible (a house, car, cash, land) or intangible (intellectual property, patents, copyrights, branding).',
    example: 'Bitcoin uses a blockchain to record all transactions. Each "block" contains a list of transactions, and it\'s linked to the previous one, creating a secure and unchangeable chain.',
  },
  {
    id: 'cache',
    term: 'Cache',
    slug: 'cache',
    definition: 'A cache is a temporary storage area that stores data so that future requests for that data can be served faster. It could be a hardware or software component.',
    example: 'Your web browser caches images and text from websites you visit frequently, so the next time you go to that site, it loads much faster because the content is already on your computer.',
  },
  {
    id: 'cdn',
    term: 'CDN',
    slug: 'cdn',
    definition: 'A Content Delivery Network (CDN) is a geographically distributed network of proxy servers and their data centers. The goal is to provide high availability and performance by distributing the service spatially relative to end-users.',
    example: 'Netflix uses a CDN to store copies of its movies and shows on servers all around the world, so when you stream a video, it comes from a server near you, reducing buffering and improving quality.',
  },
  {
    id: 'cli',
    term: 'CLI',
    slug: 'cli',
    definition: 'A Command-Line Interface (CLI) is a text-based interface used to run programs, manage computer files and interact with the computer. It is an alternative to a Graphical User Interface (GUI).',
    example: 'Instead of clicking on icons, a developer might use the CLI to navigate folders, create files, and run programs by typing commands like `cd my-project` or `npm install`.',
  },
  {
    id: 'css',
    term: 'CSS',
    slug: 'css',
    definition: 'Cascading Style Sheets (CSS) is a style sheet language used for describing the presentation of a document written in a markup language like HTML. CSS describes how HTML elements should be displayed on screen, paper, or in other media.',
    example: 'If HTML is the skeleton of a webpage, CSS is the clothing. It defines the colors, fonts, and layout, making the website visually appealing.',
  },
  {
    id: 'database',
    term: 'Database',
    slug: 'database',
    definition: 'A database is an organized collection of structured information, or data, typically stored electronically in a computer system. A database is usually controlled by a database management system (DBMS).',
    example: 'A social media app stores all user profiles, posts, comments, and likes in a database, allowing the information to be retrieved and displayed to users.',
  },
  {
    id: 'deployment',
    term: 'Deployment',
    slug: 'deployment',
    definition: 'In software development, deployment is the process of making a software application available for use. This can involve installing the software on servers, configuring it, and making it accessible to users.',
    example: 'After months of development, the team began the deployment process to push the new version of their website to the live servers for everyone to see.',
  },
  {
    id: 'dns',
    term: 'DNS',
    slug: 'dns',
    definition: 'The Domain Name System (DNS) is the phonebook of the Internet. Humans access information online through domain names, like nytimes.com or espn.com. Web browsers interact through Internet Protocol (IP) addresses. DNS translates domain names to IP addresses so browsers can load Internet resources.',
    example: 'When you type "google.com" into your browser, DNS servers find the correct IP address for Google, like 172.217.9.142, allowing your computer to connect to it.',
  },
  {
    id: 'docker',
    term: 'Docker',
    slug: 'docker',
    definition: 'Docker is a platform for developing, shipping, and running applications in containers. It allows developers to package an application with all of its dependencies into a standardized unit for software development.',
    example: 'A developer uses Docker to create a container with their web application, a database, and all necessary libraries. They can then share this single container with their team, ensuring it runs exactly the same for everyone.',
  },
  {
    id: 'encryption',
    term: 'Encryption',
    slug: 'encryption',
    definition: 'Encryption is the process of converting information or data into a code, especially to prevent unauthorized access. The reverse process, decryption, makes the encrypted information readable again.',
    example: 'Messaging apps like Signal use end-to-end encryption to scramble your messages, so only you and the person you\'re communicating with can read them.',
  },
  {
    id: 'firewall',
    term: 'Firewall',
    slug: 'firewall',
    definition: 'A firewall is a network security device that monitors incoming and outgoing network traffic and decides whether to allow or block specific traffic based on a defined set of security rules.',
    example: 'Your home internet router has a built-in firewall that acts like a security guard, preventing unauthorized access to your home network from the internet.',
  },
  {
    id: 'frontend',
    term: 'Frontend',
    slug: 'frontend',
    definition: 'The frontend of a website or software application is the part that the user interacts with directly. It is also referred to as the "client-side" of the application. It includes everything that users experience directly: text colors and styles, images, graphs and tables, buttons, colors, and navigation menu.',
    example: 'A frontend developer uses HTML, CSS, and JavaScript to build the visual elements of a website, like the sign-up form, the navigation bar, and the layout of the articles you read.',
  },
  {
    id: 'git',
    term: 'Git',
    slug: 'git',
    definition: 'Git is a distributed version control system designed to handle everything from small to very large projects with speed and efficiency. It is used for tracking changes in source code during software development.',
    example: 'A team of developers uses Git to work on the same project. Each developer can work on their own "branch" and then merge their changes back into the main project, while Git keeps track of every change made.',
  },
  {
    id: 'graphql',
    term: 'GraphQL',
    slug: 'graphql',
    definition: 'GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. It gives clients the power to ask for exactly what they need and nothing more, making it easier to evolve APIs over time.',
    example: 'Instead of making multiple API requests to get a user\'s profile, their posts, and their followers, a mobile app can use a single GraphQL query to fetch all of that specific data at once.',
  },
  {
    id: 'html',
    term: 'HTML',
    slug: 'html',
    definition: 'HyperText Markup Language (HTML) is the standard markup language for documents designed to be displayed in a web browser. It can be assisted by technologies such as Cascading Style Sheets (CSS) and scripting languages such as JavaScript.',
    example: 'HTML provides the basic structure of a webpage, like creating headings, paragraphs, and links, much like a skeleton provides the frame for a body.',
  },
  {
    id: 'http',
    term: 'HTTP/HTTPS',
    slug: 'http',
    definition: 'Hypertext Transfer Protocol (HTTP) is the foundation of data communication for the World Wide Web. HTTPS is the secure version of HTTP, where communications are encrypted.',
    example: 'When you visit a website, your browser sends an HTTP request to the server to get the page content. If you\'re on a banking site, it uses HTTPS to encrypt your login details for security.',
  },
  {
    id: 'ide',
    term: 'IDE',
    slug: 'ide',
    definition: 'An Integrated Development Environment (IDE) is a software application that provides comprehensive facilities to computer programmers for software development. An IDE normally consists of a source code editor, build automation tools, and a debugger.',
    example: 'Programmers use an IDE like Visual Studio Code, which combines a code editor, a terminal, and debugging tools all in one window to streamline their workflow.',
  },
  {
    id: 'ip-address',
    term: 'IP Address',
    slug: 'ip-address',
    definition: 'An Internet Protocol (IP) address is a numerical label assigned to each device connected to a computer network that uses the Internet Protocol for communication. An IP address serves two main functions: host or network interface identification and location addressing.',
    example: 'An IP address is like the mailing address for your computer on the internet, allowing it to send and receive data from other computers.',
  },
  {
    id: 'javascript',
    term: 'JavaScript',
    slug: 'javascript',
    definition: 'JavaScript is a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS. It enables interactive web pages and is an essential part of web applications.',
    example: 'When you click a button on a website and a pop-up appears without the page reloading, that interactivity is powered by JavaScript.',
  },
  {
    id: 'json',
    term: 'JSON',
    slug: 'json',
    definition: 'JavaScript Object Notation (JSON) is a lightweight data-interchange format. It is easy for humans to read and write and easy for machines to parse and generate. It is based on a subset of the JavaScript Programming Language.',
    example: 'When a weather app gets forecast data from a server, the server often sends it in JSON format, like {"city": "New York", "temperature": 75}, which the app can easily understand and display.',
  },
  {
    id: 'kubernetes',
    term: 'Kubernetes',
    slug: 'kubernetes',
    definition: 'Kubernetes, also known as K8s, is an open-source system for automating deployment, scaling, and management of containerized applications.',
    example: 'A large e-commerce site uses Kubernetes to manage its thousands of microservices. If one service fails, Kubernetes automatically restarts it. If traffic surges during a sale, it automatically scales up the necessary services.',
  },
  {
    id: 'lan',
    term: 'LAN',
    slug: 'lan',
    definition: 'A Local Area Network (LAN) is a collection of devices connected together in one physical location, such as a building, office, or home. A LAN can be small or large, ranging from a home network with one user to an enterprise network with thousands of users and devices in an office or school.',
    example: 'The computers, printers, and smart devices connected to your home Wi-Fi network form a LAN.',
  },
  {
    id: 'machine-learning',
    term: 'Machine Learning',
    slug: 'machine-learning',
    definition: 'Machine learning is a branch of artificial intelligence (AI) and computer science which focuses on the use of data and algorithms to imitate the way that humans learn, gradually improving its accuracy.',
    example: 'Your email service uses machine learning to identify spam by learning from the emails you and other users mark as junk.',
  },
  {
    id: 'microservices',
    term: 'Microservices',
    slug: 'microservices',
    definition: 'Microservices is an architectural style that structures an application as a collection of loosely coupled services. In a microservices architecture, services are fine-grained and the protocols are lightweight.',
    example: 'An online shopping application might be built using microservices: one service for user accounts, another for the product catalog, and a third for the shopping cart. They all work together but can be updated independently.',
  },
  {
    id: 'nosql',
    term: 'NoSQL',
    slug: 'nosql',
    definition: 'A NoSQL database provides a mechanism for storage and retrieval of data that is modeled in means other than the tabular relations used in relational databases. They are highly flexible and can handle large amounts of unstructured data.',
    example: 'A social media platform uses a NoSQL database to store user posts, which can vary greatly in structure—some have text, some have images, some have videos, making a flexible data model ideal.',
  },
  {
    id: 'oauth',
    term: 'OAuth',
    slug: 'oauth',
    definition: 'OAuth is an open standard for access delegation, commonly used as a way for Internet users to grant websites or applications access to their information on other websites but without giving them the passwords.',
    example: 'When you see a "Log in with Google" button on a website, it uses OAuth. You grant that site access to your basic Google profile information without ever giving it your Google password.',
  },
  {
    id: 'paas',
    term: 'PaaS',
    slug: 'paas',
    definition: 'Platform as a Service (PaaS) is a cloud computing model where a third-party provider delivers hardware and software tools to users over the internet. PaaS provides a platform for developers to build, run, and manage applications without the complexity of building and maintaining the infrastructure.',
    example: 'A developer uses a PaaS like Heroku to deploy their web application. They just upload their code, and Heroku handles the servers, databases, and scaling, letting the developer focus only on the app itself.',
  },
  {
    id: 'query',
    term: 'Query',
    slug: 'query',
    definition: 'A query is a request for data or information from a database. Queries can be designed to retrieve specific data, perform calculations, or automate data management tasks.',
    example: 'When you search for products on an e-commerce website, a query is sent to the database to retrieve all items that match your search criteria.',
  },
  {
    id: 'rest',
    term: 'REST',
    slug: 'rest',
    definition: 'Representational State Transfer (REST) is a software architectural style that defines a set of constraints to be used for creating Web services. Web services that conform to the REST architectural style, called RESTful Web services, provide interoperability between computer systems on the Internet.',
    example: 'Many APIs are RESTful. For example, a weather application might send a request to a URL like `api.weather.com/v1/forecast/new-york` to get the weather, which is a simple, stateless RESTful interaction.',
  },
  {
    id: 'saas',
    term: 'SaaS',
    slug: 'saas',
    definition: 'Software as a Service (SaaS) is a software distribution model in which a third-party provider hosts applications and makes them available to customers over the Internet. SaaS is one of three main categories of cloud computing, alongside infrastructure as a service (IaaS) and platform as a service (PaaS).',
    example: 'Web-based email services like Gmail, office tools like Google Docs, or customer relationship management software like Salesforce are all examples of SaaS.',
  },
  {
    id: 'sdk',
    term: 'SDK',
    slug: 'sdk',
    definition: 'A Software Development Kit (SDK) is a collection of software development tools in one installable package. They facilitate the creation of applications by having a compiler, debugger and sometimes a software framework.',
    example: 'To build an Android app, developers download the Android SDK, which includes all the libraries and tools needed to write, test, and debug applications for the Android platform.',
  },
  {
    id: 'sql',
    term: 'SQL',
    slug: 'sql',
    definition: 'Structured Query Language (SQL) is a standard language for storing, manipulating and retrieving data in relational databases. It is the standard language for Relational Database Management Systems (RDBMS).',
    example: 'A data analyst writes an SQL query like `SELECT * FROM Customers WHERE Country="Mexico";` to retrieve a list of all customers from Mexico from the company\'s database.',
  },
  {
    id: 'ssl-tls',
    term: 'SSL/TLS',
    slug: 'ssl-tls',
    definition: 'Transport Layer Security (TLS), and its now-deprecated predecessor, Secure Sockets Layer (SSL), are cryptographic protocols designed to provide communications security over a computer network. They are used in applications such as web browsing, email, and instant messaging.',
    example: 'The "https" and padlock icon in your browser\'s address bar indicate that your connection to the website is secured by SSL/TLS, encrypting the data between you and the server.',
  },
  {
    id: 'tcp-ip',
    term: 'TCP/IP',
    slug: 'tcp-ip',
    definition: 'Transmission Control Protocol/Internet Protocol (TCP/IP) is a suite of communication protocols used to interconnect network devices on the internet. It specifies how data should be packetized, addressed, transmitted, routed, and received.',
    example: 'TCP/IP is the fundamental language of the internet. When you send an email, TCP breaks it into small packets, and IP makes sure they are sent to the correct address, where TCP reassembles them.',
  },
  {
    id: 'ui',
    term: 'UI',
    slug: 'ui',
    definition: 'The User Interface (UI) is the point of human-computer interaction and communication in a device. This can include display screens, keyboards, a mouse, and the appearance of a desktop. It is also the way through which a user interacts with an application or a website.',
    example: 'The UI of a mobile app includes all the buttons you tap, the text you read, the images you see, and the way you swipe through different screens.',
  },
  {
    id: 'ux',
    term: 'UX',
    slug: 'ux',
    definition: 'User Experience (UX) refers to a person\'s emotions and attitudes about using a particular product, system or service. It includes the practical, experiential, affective, meaningful and valuable aspects of human-computer interaction and product ownership.',
    example: 'A good UX design for an e-commerce site means the process of finding a product, adding it to the cart, and checking out is smooth, intuitive, and frustration-free for the user.',
  },
  {
    id: 'virtual-machine',
    term: 'Virtual Machine',
    slug: 'virtual-machine',
    definition: 'A Virtual Machine (VM) is a digital version of a physical computer. A VM is a computer file, typically called an image, that behaves like an actual computer. It can run in a window as a separate computing environment, often to run a different operating system.',
    example: 'A developer might use a virtual machine on their Mac to run a full version of Windows, allowing them to test their software on both operating systems without needing a second computer.',
  },
  {
    id: 'vpn',
    term: 'VPN',
    slug: 'vpn',
    definition: 'A Virtual Private Network (VPN) extends a private network across a public network and enables users to send and receive data across shared or public networks as if their computing devices were directly connected to the private network.',
    example: 'An employee working from home uses a VPN to securely connect to their company\'s internal network, allowing them to access files and systems as if they were in the office.',
  },
  {
    id: 'wan',
    term: 'WAN',
    slug: 'wan',
    definition: 'A Wide Area Network (WAN) is a telecommunications network that extends over a large geographic area for the primary purpose of computer networking. WANs are often established with leased telecommunication circuits.',
    example: 'The Internet is the largest WAN, connecting billions of computers globally. A large corporation also uses a WAN to connect its office branches in different cities.',
  },
  {
    id: 'xml',
    term: 'XML',
    slug: 'xml',
    definition: 'Extensible Markup Language (XML) is a markup language and file format for storing, transmitting, and reconstructing arbitrary data. It defines a set of rules for encoding documents in a format that is both human-readable and machine-readable.',
    example: 'XML is often used for configuration files or for transmitting data between different systems. For example, an RSS feed uses an XML file to list the latest articles from a website.',
  },
  {
    id: 'yaml',
    term: 'YAML',
    slug: 'yaml',
    definition: 'YAML (YAML Ain\'t Markup Language) is a human-readable data-serialization language. It is commonly used for configuration files and in applications where data is being stored or transmitted.',
    example: 'Many modern applications use YAML for their configuration files because its syntax is clean and easy to read, using indentation to denote structure, e.g. `docker-compose.yml` or Kubernetes configs.',
  },
  {
    id: 'zip',
    term: 'ZIP',
    slug: 'zip',
    definition: 'ZIP is an archive file format that supports lossless data compression. A .zip file may contain one or more files or directories that may have been compressed. It is a common way to package and transport files.',
    example: 'To send a folder of photos via email, you might first compress it into a single .zip file to reduce the overall size and make it a single attachment.',
  },
];
